name: covidnepal
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  groovin_widgets: ^1.5.0+2
  package_info: ^0.4.0+18
  timeago: ^2.0.26
  cached_network_image: ^2.2.0+1
  toggle_switch: "^0.1.4"
  device_preview: ^0.4.5
  bubble_bottom_bar: ^1.2.0
  font_awesome_flutter: ^8.8.1
  flutter_svg: ^0.17.4
  auto_size_text: ^2.1.0
  webview_flutter: ^0.3.22+1
  url_launcher: ^5.4.10
  provider: ^4.1.3
  shared_preferences: ^0.5.7+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^0.1.9

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/json/
